version: 2.1
jobs:
  build:
    docker:
      - image: linkyard/atlassian-sdk:8.0.16
    steps:
      - checkout
      - run:
          name: Atlassian Package
          command: |
            atlas-package

      - store_artifacts:
           path: /root/project/target/*.obr
           destination: mscgen-confluence-plugin-artifact
